version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.netty:netty-resolver-dns-native-macos
    versions:
    - 4.1.63.Final
  - dependency-name: io.netty:netty-resolver-dns
    versions:
    - 4.1.63.Final
  - dependency-name: io.netty:netty-codec-dns
    versions:
    - 4.1.63.Final
  - dependency-name: io.netty:netty-transport-native-unix-common
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-transport-native-kqueue
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-transport-native-epoll
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-transport
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-resolver
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-handler-proxy
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-handler
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-common
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-codec-socks
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-codec-http2
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-codec-http
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-codec
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-buffer
    versions:
    - 4.1.62.Final
    - 4.1.63.Final
    - 4.1.63.Final
  - dependency-name: org.owasp.dependencycheck
    versions:
    - 6.1.3
    - 6.1.4
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.cloud:spring-cloud-starter-bootstrap
    versions:
    - 3.0.2
  - dependency-name: org.springframework.cloud:spring-cloud-starter-openfeign
    versions:
    - 3.0.2
  - dependency-name: org.springframework.cloud:spring-cloud-contract-wiremock
    versions:
    - 3.0.2
  - dependency-name: com.github.ben-manes.versions
    versions:
    - 0.38.0
  - dependency-name: uk.gov.hmcts.reform:idam-client
    versions:
    - 2.0.0
  - dependency-name: uk.gov.hmcts.reform:core-case-data-store-client
    versions:
    - 4.7.6
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-core
    versions:
    - 10.0.2
