management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: health, info, prometheus
  security:
    enabled: false

spring:
  application:
    name: Bulk Scan Payment Processor
  main:
    # without this, Spring can't properly resolve feign clients when IDAM and CCD clients are both included
    # TODO: remove when possible
    allow-bean-definition-overriding: true

site-mappings:
  sites:
    - siteName: PROBATE
      poBox: 12625
      siteId: ${SITE_ID_PROBATE}
    - siteName: DIVORCE
      poBox: 12706
      siteId: ${SITE_ID_DIVORCE}
    - siteName: DIVORCE
      poBox: 12746
      siteId: ${SITE_ID_FINREM}

azure:
  servicebus:
    payments:
      connection-string: ${PAYMENTS_QUEUE_READ_CONNECTION_STRING}
      write-connection-string: ${PAYMENTS_QUEUE_WRITE_CONNECTION_STRING}
      queue-name: payments
      max-delivery-count: 5

idam:
  s2s-auth:
    url: ${S2S_URL:http://localhost:4552}
    secret: ${S2S_SECRET:AAAAAAAAAAAAAAAA}
    name: ${S2S_NAME:bulk_scan_payments_processor}
  api:
    url: ${IDAM_API_URL}
  client:
    id: 'bsp'
    secret: ${IDAM_CLIENT_SECRET}
    redirect_uri: ${IDAM_CLIENT_REDIRECT_URI}
  users:
    bulkscan:
      username: ${IDAM_USERS_BULKSCAN_USERNAME:bulkscan+ccd@gmail.com}
      password: ${IDAM_USERS_BULKSCAN_PASSWORD:Password12}

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL}

scheduling:
  enabled: false
  task:
    consume-payments-queue:
      enabled: false
